spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key:
        model-name: qwen-turbo
      embedding-model:
        api-key:
        model-name: text-embedding-v4
bigmodel:
  api-key:
